# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
