# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161215_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(auto_now=True)),
                ('feature_name', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=80)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Ticker')),
            ],
        ),
    ]
