# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('text', models.TextField()),
                ('source', models.CharField(blank=True, max_length=80, null=True)),
                ('link', models.URLField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('lastsale', models.CharField(blank=True, max_length=20, null=True)),
                ('marketcap', models.CharField(blank=True, max_length=20, null=True)),
                ('ipoyear', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=30, null=True)),
                ('industry', models.CharField(blank=True, max_length=40, null=True)),
                ('summary_quate', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='currency',
            field=models.CharField(blank=True, choices=[(b'$', b'$'), (b'', b''), (b'', b'')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.NewsSummary'),
        ),
    ]
